export const COLORES = ["#FF6B35","#4ECDC4","#A78BFA","#FFD700","#FF6B9D","#51CF66","#74C0FC"];
export const MUSCULOS = ["Pecho","Hombros","Tríceps","Espalda","Bíceps","Cuádriceps","Glúteos","Isquios","Pantorrillas","Core","Cardio"];
export const EJERCICIOS_DB = [
  {id:"pe01",nombre:"Press en máquina inclinado",musculo:"Pecho"},
  {id:"pe02",nombre:"Press en máquina plano",musculo:"Pecho"},
  {id:"pe03",nombre:"Press con mancuernas inclinado",musculo:"Pecho"},
  {id:"pe04",nombre:"Press con mancuernas plano",musculo:"Pecho"},
  {id:"pe05",nombre:"Aperturas con mancuernas banco plano",musculo:"Pecho"},
  {id:"pe06",nombre:"Aperturas con mancuernas inclinado",musculo:"Pecho"},
  {id:"pe07",nombre:"Cruces en polea alta",musculo:"Pecho"},
  {id:"pe08",nombre:"Cruces en polea baja",musculo:"Pecho"},
  {id:"pe09",nombre:"Fondos en paralelas",musculo:"Pecho"},
  {id:"pe10",nombre:"Pullover con mancuerna",musculo:"Pecho"},
  {id:"ho01",nombre:"Press de hombros en máquina",musculo:"Hombros"},
  {id:"ho02",nombre:"Press militar con barra",musculo:"Hombros"},
  {id:"ho03",nombre:"Press Arnold con mancuernas",musculo:"Hombros"},
  {id:"ho04",nombre:"Elevaciones laterales con mancuernas",musculo:"Hombros"},
  {id:"ho05",nombre:"Elevaciones laterales en polea baja",musculo:"Hombros"},
  {id:"ho06",nombre:"Face pull en polea alta",musculo:"Hombros",tag:"🦴 salud"},
  {id:"ho07",nombre:"Pájaros con mancuernas",musculo:"Hombros"},
  {id:"ho08",nombre:"Remo al mentón con barra",musculo:"Hombros"},
  {id:"tr01",nombre:"Tríceps en polea con cuerda",musculo:"Tríceps"},
  {id:"tr02",nombre:"Extensión tríceps sobre cabeza en polea",musculo:"Tríceps"},
  {id:"tr03",nombre:"Skull crusher con barra",musculo:"Tríceps"},
  {id:"tr04",nombre:"Patada de tríceps con mancuerna",musculo:"Tríceps"},
  {id:"tr05",nombre:"Fondos en banco",musculo:"Tríceps"},
  {id:"es01",nombre:"Remo con apoyo de pecho en máquina",musculo:"Espalda"},
  {id:"es02",nombre:"Jalón al pecho agarre ancho",musculo:"Espalda"},
  {id:"es03",nombre:"Jalón agarre neutro/cerrado",musculo:"Espalda"},
  {id:"es04",nombre:"Remo unilateral con mancuerna",musculo:"Espalda"},
  {id:"es05",nombre:"Remo con barra",musculo:"Espalda"},
  {id:"es06",nombre:"Remo en polea baja sentado",musculo:"Espalda"},
  {id:"es07",nombre:"Pull over en polea",musculo:"Espalda"},
  {id:"es08",nombre:"Dominadas",musculo:"Espalda"},
  {id:"es09",nombre:"Hiperextensiones en banco romano",musculo:"Espalda"},
  {id:"bi01",nombre:"Curl en máquina",musculo:"Bíceps"},
  {id:"bi02",nombre:"Curl martillo con mancuernas",musculo:"Bíceps"},
  {id:"bi03",nombre:"Curl con barra",musculo:"Bíceps"},
  {id:"bi04",nombre:"Curl concentrado con mancuerna",musculo:"Bíceps"},
  {id:"bi05",nombre:"Curl en polea baja",musculo:"Bíceps"},
  {id:"bi06",nombre:"Curl predicador en máquina",musculo:"Bíceps"},
  {id:"cu01",nombre:"Prensa rango limitado (no pasar 90°)",musculo:"Cuádriceps",tag:"🦵 rodilla"},
  {id:"cu02",nombre:"Prensa rango completo",musculo:"Cuádriceps"},
  {id:"cu03",nombre:"Leg extension en máquina",musculo:"Cuádriceps"},
  {id:"cu04",nombre:"Isométrico leg extension a 60°",musculo:"Cuádriceps",tag:"🏥 tendinitis"},
  {id:"cu05",nombre:"Sentadilla con barra",musculo:"Cuádriceps"},
  {id:"cu06",nombre:"Sentadilla en máquina Smith",musculo:"Cuádriceps"},
  {id:"cu07",nombre:"Hack squat en máquina",musculo:"Cuádriceps"},
  {id:"cu08",nombre:"Step up con mancuernas",musculo:"Cuádriceps"},
  {id:"cu09",nombre:"Zancadas con mancuernas",musculo:"Cuádriceps"},
  {id:"gl01",nombre:"Hip thrust en máquina o barra",musculo:"Glúteos",tag:"💪 clave"},
  {id:"gl02",nombre:"Hip thrust con banda elástica",musculo:"Glúteos"},
  {id:"gl03",nombre:"Abducción de cadera en máquina",musculo:"Glúteos"},
  {id:"gl04",nombre:"Patada de glúteo en polea baja",musculo:"Glúteos"},
  {id:"gl05",nombre:"Peso muerto rumano con barra",musculo:"Glúteos"},
  {id:"gl06",nombre:"Peso muerto rumano con mancuernas",musculo:"Glúteos"},
  {id:"is01",nombre:"Leg curl acostado en máquina",musculo:"Isquios"},
  {id:"is02",nombre:"Leg curl sentado en máquina",musculo:"Isquios"},
  {id:"is03",nombre:"Leg curl excéntrico (bajada 3 seg)",musculo:"Isquios",tag:"🦵 rodilla"},
  {id:"is04",nombre:"Peso muerto piernas rígidas",musculo:"Isquios"},
  {id:"pa01",nombre:"Pantorrilla en máquina de pie",musculo:"Pantorrillas"},
  {id:"pa02",nombre:"Pantorrilla unilateral con mancuerna",musculo:"Pantorrillas"},
  {id:"pa03",nombre:"Pantorrilla sentado en máquina",musculo:"Pantorrillas"},
  {id:"co01",nombre:"Plancha frontal",musculo:"Core"},
  {id:"co02",nombre:"Plancha lateral",musculo:"Core"},
  {id:"co03",nombre:"Pallof press en polea",musculo:"Core",tag:"🏀 básquet"},
  {id:"co04",nombre:"Dead bug",musculo:"Core",tag:"🏀 básquet"},
  {id:"co05",nombre:"Crunch en máquina",musculo:"Core"},
  {id:"co06",nombre:"Elevación de piernas colgado",musculo:"Core"},
  {id:"co07",nombre:"Rueda abdominal",musculo:"Core"},
  {id:"co08",nombre:"Crunch en polea alta",musculo:"Core"},
  {id:"ca01",nombre:"Elíptico",musculo:"Cardio",tag:"🦵 bajo impacto"},
  {id:"ca02",nombre:"Bicicleta estática",musculo:"Cardio",tag:"🦵 bajo impacto"},
  {id:"ca03",nombre:"Cinta de correr",musculo:"Cardio"},
  {id:"ca04",nombre:"Remo ergómetro",musculo:"Cardio"},
  {id:"ca05",nombre:"Saltar soga",musculo:"Cardio"},
];
